# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "test"

[dependencies]
deno_core = "0.202.0"
deno_runtime = "0.123.0"
tokio = "1.32.0"
